// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOgZYA0M_m81rdlVAwgp80Z5yV6NaZ2Yg',
    appId: '1:1033622455717:web:6198155c5196e7e5ff944c',
    messagingSenderId: '1033622455717',
    projectId: 'uangku-ichsan',
    authDomain: 'uangku-ichsan.firebaseapp.com',
    storageBucket: 'uangku-ichsan.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtlfMx1hwYVBsEsewM7QAi87fcPhnGjYs',
    appId: '1:1033622455717:android:7227816ba5ad49dbff944c',
    messagingSenderId: '1033622455717',
    projectId: 'uangku-ichsan',
    storageBucket: 'uangku-ichsan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVqy-zxdvLZkJo8R5yrJHiHII58eNznvE',
    appId: '1:1033622455717:ios:47f965b8506f1259ff944c',
    messagingSenderId: '1033622455717',
    projectId: 'uangku-ichsan',
    storageBucket: 'uangku-ichsan.firebasestorage.app',
    iosBundleId: 'com.example.uangku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVqy-zxdvLZkJo8R5yrJHiHII58eNznvE',
    appId: '1:1033622455717:ios:47f965b8506f1259ff944c',
    messagingSenderId: '1033622455717',
    projectId: 'uangku-ichsan',
    storageBucket: 'uangku-ichsan.firebasestorage.app',
    iosBundleId: 'com.example.uangku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOgZYA0M_m81rdlVAwgp80Z5yV6NaZ2Yg',
    appId: '1:1033622455717:web:b73639aada4531b7ff944c',
    messagingSenderId: '1033622455717',
    projectId: 'uangku-ichsan',
    authDomain: 'uangku-ichsan.firebaseapp.com',
    storageBucket: 'uangku-ichsan.firebasestorage.app',
  );
}
